#include <iostream>
using namespace std;

int main() {
    try {
        int a = 10, b = 0;
        if (b == 0) {
            throw runtime_error("Division by zero error");
        }
        cout << a / b << endl;
    } catch (const runtime_error& e) {
        cout << "Exception: " << e.what() << endl;
    }
    return 0;
}
